// Code generated by MockGen. DO NOT EDIT.
// Source: deps.go
//
// Generated by this command:
//
//	mockgen -source=deps.go -package=service -destination=deps_mock.go
//

// Package service is a generated GoMock package.
package service

import (
	context "context"
	reflect "reflect"

	event "github.com/feanchy/Order-Service/internal/event"
	model "github.com/feanchy/Order-Service/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockOrderRepository is a mock of OrderRepository interface.
type MockOrderRepository struct {
	ctrl     *gomock.Controller
	recorder *MockOrderRepositoryMockRecorder
	isgomock struct{}
}

// MockOrderRepositoryMockRecorder is the mock recorder for MockOrderRepository.
type MockOrderRepositoryMockRecorder struct {
	mock *MockOrderRepository
}

// NewMockOrderRepository creates a new mock instance.
func NewMockOrderRepository(ctrl *gomock.Controller) *MockOrderRepository {
	mock := &MockOrderRepository{ctrl: ctrl}
	mock.recorder = &MockOrderRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderRepository) EXPECT() *MockOrderRepositoryMockRecorder {
	return m.recorder
}

// CreateOrder mocks base method.
func (m *MockOrderRepository) CreateOrder(ctx context.Context) (*model.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrder", ctx)
	ret0, _ := ret[0].(*model.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOrder indicates an expected call of CreateOrder.
func (mr *MockOrderRepositoryMockRecorder) CreateOrder(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrder", reflect.TypeOf((*MockOrderRepository)(nil).CreateOrder), ctx)
}

// Get mocks base method.
func (m *MockOrderRepository) Get(ctx context.Context, id int) (*model.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*model.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockOrderRepositoryMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockOrderRepository)(nil).Get), ctx, id)
}

// List mocks base method.
func (m *MockOrderRepository) List(ctx context.Context) ([]*model.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]*model.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockOrderRepositoryMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockOrderRepository)(nil).List), ctx)
}

// MockOrderProducer is a mock of OrderProducer interface.
type MockOrderProducer struct {
	ctrl     *gomock.Controller
	recorder *MockOrderProducerMockRecorder
	isgomock struct{}
}

// MockOrderProducerMockRecorder is the mock recorder for MockOrderProducer.
type MockOrderProducerMockRecorder struct {
	mock *MockOrderProducer
}

// NewMockOrderProducer creates a new mock instance.
func NewMockOrderProducer(ctrl *gomock.Controller) *MockOrderProducer {
	mock := &MockOrderProducer{ctrl: ctrl}
	mock.recorder = &MockOrderProducerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderProducer) EXPECT() *MockOrderProducerMockRecorder {
	return m.recorder
}

// PublishOrderCreated mocks base method.
func (m *MockOrderProducer) PublishOrderCreated(ctx context.Context, arg1 event.OrderCreated) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishOrderCreated", ctx, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishOrderCreated indicates an expected call of PublishOrderCreated.
func (mr *MockOrderProducerMockRecorder) PublishOrderCreated(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishOrderCreated", reflect.TypeOf((*MockOrderProducer)(nil).PublishOrderCreated), ctx, arg1)
}

// MockOrderEventHandler is a mock of OrderEventHandler interface.
type MockOrderEventHandler struct {
	ctrl     *gomock.Controller
	recorder *MockOrderEventHandlerMockRecorder
	isgomock struct{}
}

// MockOrderEventHandlerMockRecorder is the mock recorder for MockOrderEventHandler.
type MockOrderEventHandlerMockRecorder struct {
	mock *MockOrderEventHandler
}

// NewMockOrderEventHandler creates a new mock instance.
func NewMockOrderEventHandler(ctrl *gomock.Controller) *MockOrderEventHandler {
	mock := &MockOrderEventHandler{ctrl: ctrl}
	mock.recorder = &MockOrderEventHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderEventHandler) EXPECT() *MockOrderEventHandlerMockRecorder {
	return m.recorder
}

// HandleOrderCreated mocks base method.
func (m *MockOrderEventHandler) HandleOrderCreated(ctx context.Context, arg1 event.OrderCreated) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleOrderCreated", ctx, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// HandleOrderCreated indicates an expected call of HandleOrderCreated.
func (mr *MockOrderEventHandlerMockRecorder) HandleOrderCreated(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleOrderCreated", reflect.TypeOf((*MockOrderEventHandler)(nil).HandleOrderCreated), ctx, arg1)
}
